[supervisord]
logfile=logs/supervisord.log
pidfile=supervisord.pid

[program:opend_303698]
directory=303698
command=FutuOpenD
autostart=false
autorestart=true
stdout_logfile=logs/opend_303698.out.log
stderr_logfile=logs/opend_303698.err.log

[program:ft_303698]
directory=303698
command=python3 fight.py
autostart=false
autorestart=true
stdout_logfile=logs/ft_303698.out.log
stderr_logfile=logs/ft_303698.err.log

[program:opend_320451]
directory=320451
command=FutuOpenD
autostart=false
autorestart=true
stdout_logfile=logs/opend_320451.out.log
stderr_logfile=logs/opend_320451.err.log

[program:ft_320451]
directory=320451
command=python3 fight.py
autostart=false
autorestart=true
stdout_logfile=logs/ft_320451.out.log
stderr_logfile=logs/ft_320451.err.log
