[supervisord]
logfile=logs/supervisord.log
pidfile=supervisord.pid
loglevel=INFO

[inet_http_server]
port = *:39001

[supervisorctl]
serverurl=http://127.0.0.1:39001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:opend_303698]
directory=/data/release/ft
command=/data/release/ft/303698/FutuOpenD
loglevel=DEBUG
priority=10
autostart=false
autorestart=true
stdout_logfile=logs/opend_303698.out.log
stderr_logfile=logs/opend_303698.err.log

[program:ft_303698]
directory=/data/release/ft
command=python3 /data/release/ft/303698/fight.py
priority=20
autostart=false
autorestart=true
stderr_logfile=logs/ft_303698.err.log

[program:opend_320451]
directory=/data/release/ft
command=/data/release/ft/320451/FutuOpenD
loglevel=DEBUG
priority=10
autostart=false
autorestart=true
stdout_logfile=logs/opend_320451.out.log
stderr_logfile=logs/opend_320451.err.log

[program:ft_320451]
directory=/data/release/ft
command=python3 /data/release/ft/320451/fight.py
priority=20
autostart=false
autorestart=true
stderr_logfile=logs/ft_320451.err.log
