[supervisord]
logfile=logs/supervisord.log
pidfile=supervisord.pid
loglevel=INFO

[inet_http_server]
port = *:39001

[supervisorctl]
serverurl=http://127.0.0.1:39001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
